/* ═══════════════════════════════════════════════════════════
   main.js — Entry point, dispatched by data-page attribute
   ═══════════════════════════════════════════════════════════ */

import { BackgroundManager } from './background-manager.js';
import { initNav } from './nav.js';

/** Dismiss the portal arrival overlay */
function dismissPortalOverlay() {
  const el = document.getElementById('portal-arrival');
  if (el) {
    el.style.opacity = '0';
    el.style.pointerEvents = 'none';
    el.style.transition = 'opacity 0.3s ease';
  }
}

document.addEventListener('DOMContentLoaded', async () => {
  console.log('%c 群星之间 · 编年史 %c MULTI-PAGE ',
    'color:#c9a050;font-size:20px;font-family:serif;',
    'color:#9a9078;font-size:11px;');

  // Init background engine
  BackgroundManager.init('bg-canvas', 'bg-video', 'bg-image');

  const pageType = document.body.dataset.page;

  if (pageType === 'star-map') {
    // Dismiss portal overlay immediately — star map has no arrival animation
    dismissPortalOverlay();

    // Star map home page
    const { initStarMap } = await import('./star-map.js');
    initStarMap();
    BackgroundManager.switchTo('star-map');
    initNav();

  } else if (pageType === 'world') {
    // World timeline page — portal arrival is handled by initPortalArrival()
    const worldId = document.body.dataset.world;
    console.log('%c 加载世界: ' + worldId, 'color:#d4923a;');

    const { loadTimelineData } = await import('./data-loader.js');
    const { populateBranchTabs, renderEvents, updateTimelineCover } = await import('./timeline-ui.js');

    // Init background with world preset
    const { WORLDS } = await import('./worlds.js');
    const world = WORLDS[worldId];
    if (world) {
      BackgroundManager.switchTo(world.bgPreset);
    }

    initNav();

    try {
      await loadTimelineData(worldId);
      populateBranchTabs();
      renderEvents('mainline');
      updateTimelineCover(worldId);
    } catch (err) {
      console.error('Failed to load world data:', err);
      document.querySelector('.tl-cover h1').textContent = '数据加载失败';
      document.querySelector('.tl-cover p').textContent = '请确保 data/' + worldId + '.json 存在，或使用 npm run build 构建';
      // Dismiss portal even on error
      dismissPortalOverlay();
    }

    // Portal arrival animation (will dismiss portal after animation)
    const { initPortalArrival } = await import('./portal-transition.js');
    initPortalArrival();

  } else if (pageType === 'about') {
    // Dismiss portal overlay — about page doesn't need it
    dismissPortalOverlay();

    // About page — just background + nav
    BackgroundManager.switchTo('star-map');
    initNav();
  }
});

/**
 * Global handler: cross-world reference click → portal outgoing
 * Attached on document ready for event cards generated by VirtualTimeline
 */
document.addEventListener('click', (e) => {
  const link = e.target.closest('.cross-world-link');
  if (!link) return;

  const worldId = link.dataset.world;
  const eventId = link.dataset.target;
  if (!worldId) return;

  const targetUrl = './' + worldId + '.html' + (eventId ? '#' + eventId : '');

  import('./portal-transition.js').then(({ playPortalOutgoing }) => {
    playPortalOutgoing(e, targetUrl);
  });
});
