const esbuild = require('esbuild');
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const DIST = path.join(__dirname, 'dist');
const SRC_JS = path.join(__dirname, 'src', 'js', 'modules');
const LIB_JS = path.join(__dirname, 'src', 'js', 'lib');

async function buildJS() {
  console.log('[esbuild] Bundling JS...');

  // Bundle ES modules into IIFE
  await esbuild.build({
    entryPoints: [path.join(SRC_JS, 'main.js')],
    bundle: true,
    format: 'iife',
    globalName: 'AK',
    outfile: path.join(DIST, 'js', 'bundle.js'),
    splitting: false,
    target: 'es2020',
    minify: false,
    sourcemap: true,
    external: ['virtual-timeline.js'], // Don't bundle virtual-timeline
    // Stub out the import of virtual-timeline since it's loaded separately
    banner: {
      js: '// Bundle generated by esbuild\n// virtual-timeline.js loaded separately',
    },
    logLevel: 'info',
  });

  // Copy virtual-timeline.js to dist
  fs.mkdirSync(path.join(DIST, 'js'), { recursive: true });
  fs.copyFileSync(
    path.join(LIB_JS, 'virtual-timeline.js'),
    path.join(DIST, 'js', 'virtual-timeline.js')
  );

  console.log('[esbuild] JS bundle complete.');
}

async function buildCSS() {
  console.log('[build] Copying CSS...');
  fs.mkdirSync(path.join(DIST, 'css'), { recursive: true });
  const cssDir = path.join(__dirname, 'src', 'css');
  const files = fs.readdirSync(cssDir).filter(f => f.endsWith('.css'));
  for (const f of files) {
    fs.copyFileSync(path.join(cssDir, f), path.join(DIST, 'css', f));
  }
}

async function main() {
  console.log('========================================');
  console.log('  群星之间 · 编年史 — Build');
  console.log('========================================\n');

  // Step 1: Run 11ty to build HTML
  console.log('[11ty] Building HTML...');
  try {
    execSync('npx @11ty/eleventy', { stdio: 'inherit', cwd: __dirname });
  } catch (e) {
    console.error('[11ty] HTML build failed:', e.message);
    // Continue anyway — dist/js may not exist yet
  }
  console.log('');

  // Step 2: Build JS bundle
  try {
    await buildJS();
  } catch (e) {
    console.error('[esbuild] JS build failed:', e.message);
  }
  console.log('');

  // Step 3: Copy CSS
  await buildCSS();

  console.log('\n========================================');
  console.log('  Build complete! Output: dist/');
  console.log('========================================');
}

main().catch(console.error);
