const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const DIST = path.join(__dirname, 'dist');
const SRC_JS = path.join(__dirname, 'src', 'js', 'modules');
const LIB_JS = path.join(__dirname, 'src', 'js', 'lib');

async function buildJS() {
  console.log('[esbuild] Bundling JS...');

  // Bundle main.js → bundle.js (world pages, about, changelog)
  await esbuild.build({
    entryPoints: [path.join(SRC_JS, 'main.js')],
    bundle: true,
    format: 'iife',
    globalName: 'AK',
    outfile: path.join(DIST, 'js', 'bundle.js'),
    splitting: false,
    target: 'es2020',
    minify: false,
    sourcemap: true,
    external: ['virtual-timeline.js'],
    banner: {
      js: '// Bundle generated by esbuild\n// virtual-timeline.js loaded separately',
    },
    logLevel: 'info',
  });

  // Bundle star-map-3d.js → star-map-3d.js (star map page only, includes Three.js)
  await esbuild.build({
    entryPoints: [path.join(SRC_JS, 'star-map-3d.js')],
    bundle: true,
    format: 'iife',
    globalName: 'SM3D',
    outfile: path.join(DIST, 'js', 'star-map-3d.js'),
    splitting: false,
    target: 'es2020',
    minify: false,
    sourcemap: true,
    logLevel: 'info',
  });

  // Copy virtual-timeline.js to dist
  fs.mkdirSync(path.join(DIST, 'js'), { recursive: true });
  fs.copyFileSync(
    path.join(LIB_JS, 'virtual-timeline.js'),
    path.join(DIST, 'js', 'virtual-timeline.js')
  );

  console.log('[esbuild] JS bundles complete.');
}

async function buildCSS() {
  console.log('[build] Copying CSS...');
  fs.mkdirSync(path.join(DIST, 'css'), { recursive: true });
  const cssDir = path.join(__dirname, 'src', 'css');
  const files = fs.readdirSync(cssDir).filter(f => f.endsWith('.css'));
  for (const f of files) {
    fs.copyFileSync(path.join(cssDir, f), path.join(DIST, 'css', f));
  }
}

async function main() {
  console.log('========================================');
  console.log('  群星之间 · 编年史 — Build');
  console.log('========================================\n');

  // Step 1: Build JS bundles
  try {
    await buildJS();
  } catch (e) {
    console.error('[esbuild] JS build failed:', e.message);
    process.exit(1);
  }
  console.log('');

  // Step 2: Copy CSS
  await buildCSS();

  // Step 3: Verify critical output files
  const criticalFiles = [
    'js/bundle.js',
    'js/star-map-3d.js',
    'js/virtual-timeline.js',
  ];
  for (const f of criticalFiles) {
    const fp = path.join(DIST, f);
    if (!fs.existsSync(fp)) {
      console.error(`[build] Missing critical file: ${f}`);
      process.exit(1);
    }
  }

  console.log('\n========================================');
  console.log('  Build complete! Output: dist/');
  console.log('========================================');
}

main().catch(console.error);